name: Apt based Linux
on:
  push:
    branches:
      - master
      - fluent-package-lts-v5
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        label:
          - Debian GNU/Linux bullseye amd64
          - Debian GNU/Linux bookworm amd64
          - Ubuntu Focal amd64
          - Ubuntu Jammy amd64
        include:
          - label: Debian GNU/Linux bullseye amd64
            rake-job: debian-bullseye
            test-docker-image: debian:bullseye
          - label: Debian GNU/Linux bookworm amd64
            rake-job: debian-bookworm
            test-docker-image: debian:bookworm
          - label: Ubuntu Focal amd64
            rake-job: ubuntu-focal
            test-docker-image: ubuntu:focal
          - label: Ubuntu Jammy amd64
            rake-job: ubuntu-jammy
            test-docker-image: ubuntu:jammy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install ruby ruby-bundler ruby-serverspec
          sudo gem install bundler:2.2.9 --no-document
          sudo gem uninstall fileutils
      - name: Build deb with Docker
        run: |
          rake apt:build APT_TARGETS=${{ matrix.rake-job }}
      - name: Upload fluent-package deb
        uses: actions/upload-artifact@master
        with:
          name: packages-${{ matrix.rake-job }}
          path: fluent-package/apt/repositories
      - name: Upload fluent-apt-source deb
        uses: actions/upload-artifact@master
        with:
          name: packages-apt-source-${{ matrix.rake-job }}
          path: fluent-apt-source/apt/repositories
      # TODO move the following steps to "Test" job
      - name: Check Package Size
        run: |
          fluent-package/apt/pkgsize-test.sh ${{ matrix.rake-job }} amd64
      - name: Installation Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/apt/install-test.sh
      - name: Piuparts (Install/Remove/Upgrade) Test
        run: |
          mkdir -p .bundle
          docker run \
          --privileged \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/apt/piuparts-test.sh
      - name: Serverspec Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/apt/serverspec-test.sh
      - name: Binstubs Test
        run: |
          mkdir -p .bundle
          docker run \
          --rm \
          --tty \
          --volume ${PWD}:/fluentd:ro \
          ${{ matrix.test-docker-image }} \
          /fluentd/fluent-package/apt/binstubs-test.sh
  test:
    name: Test
    needs: build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - debian-bullseye
          - debian-bookworm
          - ubuntu-focal
          - ubuntu-jammy
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: packages-${{ matrix.distribution }}
      - uses: actions/download-artifact@master
        with:
          name: packages-apt-source-${{ matrix.distribution }}
      - name: Run Test
        run: fluent-package/apt/systemd-test/test.sh ${{ matrix.distribution }}
