name: macOS
on:
  push:
    branches: [td-agent-v4]
  pull_request:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install cmake
        run: |
          brew install cmake
      - name: Install gems
        run: |
          gem install bundler builder
      - name: Build
        run: |
          sudo mkdir /opt/td-agent
          sudo chown $(whoami) /opt/td-agent
          rm -rf td-agent/staging
          rake dmg:selfbuild
      - name: Upload td-agent dmg
        uses: actions/upload-artifact@master
        with:
          name: packages-macos
          path: td-agent/dmg/*.dmg
